apiVersion: apps/v1
kind: Deployment
metadata: 
  name: lms-api
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: lms-api
  template: 
    metadata: 
      labels:
        app: lms-api
    spec:
      containers:
        - name: lms-api
          image: shruti02/lms-api.jar
          imagePullPolicy: Always
          ports: 
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: lms-api
spec: 
  type: LoadBalancer
  selector: 
    app: lms-api
  ports: 
  - port: 80
    targetPort: 8080